# Generated by Django 4.1.1 on 2023-05-28 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0009_rename_pin_code_orders_zip_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
