# Generated by Django 4.1.1 on 2023-05-28 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0010_delete_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('card', models.CharField(max_length=14)),
                ('date', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
            ],
        ),
    ]
