# Generated by Django 4.1.1 on 2023-05-28 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0011_payment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
