# Generated by Django 4.1.1 on 2023-05-28 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resale', '0012_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('card', models.IntegerField(max_length=14)),
                ('expiry', models.DateField()),
                ('cvv', models.IntegerField(max_length=4)),
            ],
        ),
    ]
